export const useMatch=()=>{
    const mbtiList =[
        {
            id:1,
            mbti:'ISTJ',
            text:""    
        },
        {
            id:2,
            mbti:'ISFJ',
            text:""    
        },
        {
            id:3,
            mbti:'ESTJ',
            text:""    
        },
        {
            id:4,
            mbti:'ESTJ',
            text:""    
        },
        {
            id:5,
            mbti:'INFJ',
            text:""    
        },
        {
            id:6,
            mbti:'INTJ',
            text:""    
        },
        {
            id:7,
            mbti:'ENTJ',
            text:""    
        },
        {
            id:8,
            mbti:'ISFP',
            text:""    
        },
        {
            id:9,
            mbti:'ENFP',
            text:""    
        },
        {
            id:10,
            mbti:'INTP',
            text:""    
        },
        {
            id:11,
            mbti:'INFP',
            text:""    
        },
        {
            id:12,
            mbti:'ENFJ',
            text:""    
        },
        {
            id:13,
            mbti:'ENTP',
            text:""    
        },
        {
            id:14,
            mbti:'ESFP',
            text:""    
        },
        {
            id:15,
            mbti:'ESTP',
            text:""    
        },
        {
            id:16,
            mbti:'ISTP',
            text:""    
        }
]
    return{
        mbtiList,
    }
}